name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 15 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        include:
          - scala: 2.11.12
          - scala: 2.13.6
          - scala: 2.13.6
    steps:
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.8"
    - uses: actions/checkout@v2.3.4
    - uses: coursier/cache-action@v6
    - run: sbt -v
           "set Test / g8 / g8Properties ~= { _ + (\"scala_version\" -> \"${{ matrix.scala }}\")}"
           g8Test
